### ISSUE TITLE
Name and Org fields for Users

### ISSUE THREAD

**Issue by justinnoah** [15thnight/15thnight#108]
User model needs a name field and an organization field that can be edited in the user profile.

Shall we also show these as optional fields in the registration form?

@spectralsun

**Comment by justinnoah** [comment]
This new info should be sent to the provider when an Advocate responds.

**Comment by markdav-is** [comment]
they are asking for org info in the alert so "kids needs help send by mark at 4J"  so an org field would be nice.

**Comment by justinnoah** [comment]
@spectralsun The User model now has (and has had for a while) the fields. Should we close this or re-purposed or closed and a new one opened?

**Comment by nobane** [comment]
closed via #111
