### ISSUE TITLE
Advocates - Previous alerts only showing TODO

### ISSUE THREAD

**Issue by justinnoah** [15thnight/15thnight#113]
Previous alerts are just showing TODO.

**Comment by nobane** [comment]
We no longer have a notion of "dashboard" so please clarify the specific page/column of table you are referring to. Screenshots appreciated.

**Comment by justinnoah** [comment]
@spectralsun looks like the title is misleading a bit, though the meat of the issue-the first comment-doesn't refer to the dashboard at all, just previous alerts. Perhaps this isn't quite as invalid as the title suggests.

**Comment by justinnoah** [comment]
As seen here:

![2016-08-28-004507_1663x233_scrot](https://cloud.githubusercontent.com/assets/443413/18030902/ee94480e-6cb8-11e6-9a82-4317a54ed990.png)

**Comment by nobane** [comment]
Viewing responses functionality has been added.
