### ISSUE TITLE
Help pages

### ISSUE THREAD

**Issue by markdav-is** [15thnight/15thnight#152]
From Mike,

The issue that I wasn't aware of until the conference call is that most end-users shouldn't contact us directly.  Instead they should contact their own internal IT, such as at the schools.  The solution we discussed is to generate a different help page depending on their role.  Advocates would be instructed to reach out to their local IT resources, whereas providers would be provided with a form to request support.  Is this feature in the works?

The help page form for providers hopefully would only include a description field and a submit button.  The submit button would send an e-mail to our ticketing system at itsupport@oslc.org.  The body of the e-mail would include the description field, and the name of the provider.  The from address would need to be the providers e-mail address and the subject "15th Night RAN Website Support Request".  If you can accomplish this, then a ticket would be generated with all the information we need.  The end-user would get an automatic response initially, and then we could provide prompt service from any of the 3 of us here in IT.

**Comment by markdav-is** [comment]
this is the #1 thing on the go-live list so far.  It's a new feature.  We are getting more info on the different pages.  Do we have the ability to send an email?

**Comment by markdav-is** [comment]
Any movement on this one @spectralsun ?

**Comment by nobane** [comment]
Yes, it is mostly complete. Waiting on content to insert.

**Comment by markdav-is** [comment]
groovy.  let me know if I can help get anything from the customer for you.

**Comment by nobane** [comment]
@nohorse Can you conjure up the content for the advocate page? I think what is expected for the provider support page is pretty straight forward.

**Comment by markdav-is** [comment]
I'm on it!

**Comment by markdav-is** [comment]
more info from mike:  I took some time off, but I'm back at it and getting caught up.

I'm not certain just what we should put on the help page because I'm not as familiar with the arrangements Megan has established with advocates and providers, but I'll give it a shot and will submit the first draft.

Advocates

I believe end-user advocates should not be contacting us directly, and instead they should contact their organizations IT support.  If that is the case then I propose adding only the following text.

Please contact your organizations IT support for assistance with this website.

Providers

Please explain the issue in the box below and then click on the submit button.  A helpdesk ticket will be created and we will respond to your Email address <Email Address> ASAP.

text box here

Submit button

**Comment by nobane** [comment]
closed via #169
