### ISSUE TITLE
non-chrome browsers need testing

### ISSUE THREAD

**Issue by markdav-is** [15thnight/15thnight#153]
We are getting reports form the field that FF, Safari just give a blank page at 15thNight.help.  I have not re-created this but for now we are telling folks to use chrome.  I only care the about latest version of FF, IE, Edge, Safari.  Its OK to work best on Chrome in my book but the blank page is bummer.  If nothing else, make a screen that tells them to use chrome.

**Comment by markdav-is** [comment]
@justinnoah  you feel like taking a look at this?

**Comment by nobane** [comment]
This smells like a user error... We both develop in firefox. Safari looks like it is working just fine.

Might be a certificate issue for some firefox users, I am getting this on Firefox 47 for Mac:

<img width="659" alt="image 2016-10-07 at 1 59 53 pm" src="https://cloud.githubusercontent.com/assets/2507359/19205303/6d80891e-8c96-11e6-94dc-a9c64ee0917c.png">

**Comment by markdav-is** [comment]
Thanks for the input.  If I can get more data I'll open this back up.

**Comment by justinnoah** [comment]
@nohorse just saw the alert for this. To reiterate what @spectralsun mentioned above the issue does smell like user error. I use Firefox as my browser of choice (while testing in others as well) and hadn't noticed any Firefox only issues, let alone a blank page. Possibly a refresh/hard-refresh may be necessary for some.
