### ISSUE TITLE
change passwordlink broken

### ISSUE THREAD

**Issue by markdav-is** [15thnight/15thnight#156]
From Megan.  I have not reproduced this myself.

An advocate forgot her password so she clicked on the "forgot password" prompt and entered her email.  The link that was sent to her email did not work.  

I went in as an administrator and changed her password from my end so she is able to access the RAN but we should look into the "link"

**Comment by justinnoah** [comment]
@nohorse I'll take a look tonight. @spectralsun I will also add a test to verify this doesn't fail.

**Comment by justinnoah** [comment]
It looks like url_for is using the configuration variable SERVER_NAME when generating an externally usable link (what we need for the emails). However, we have our configuration option called HOST_NAME.

I propose a configuration change from HOST_NAME to SERVER_NAME. I believe that will correct the issue.
