### ISSUE TITLE
Latest Updates Broke Login

### ISSUE THREAD

**Issue by oslcit** [15thnight/15thnight#171]
We updated www.15thnight.help via "git pull" and restarted services yesterday, but this broke login.  On the web interface the message "An unknown error occured while logging in." was displayed.  The password reset page also didn't work and displayed a similar error.  I didn't see anything in the Apache or messages logs, although I didn't expect to fine anything relevant in these logs.  Celery log looked OK, but I also didn't think this would be relevant to login.  I wasn't sure where else to look and so I decided rollback the changes from yesterday.  I can now login and I believe the site is fine, but we'll need to identify he issue so we can update the server again.

Below is the output from "git pull" that resulted in breaking login.  Possibly you can review one of these 21 files and identify the issue, but if you need more information from us please advise how we can better assist you with troubleshooting the issue.

CHANGELOG | 2 +
_15thnight/__init__.py | 14 ++--
_15thnight/api/account.py | 57 ++++++----------
_15thnight/api/alert.py | 10 +--
_15thnight/api/category.py | 12 ++--
_15thnight/api/need.py | 4 +-
_15thnight/api/response.py | 8 +--
_15thnight/api/service.py | 10 +--
_15thnight/api/user.py | 10 +--
_15thnight/core.py | 60 ++++++++++++++++-
_15thnight/templates/email/support_request.txt | 5 ++
client/src/actions/account.js | 28 ++++++--
client/src/components/chrome/NavbarLinks.js | 6 ++
client/src/components/chrome/index.css | 2 +-
.../components/pages/advocate/AdvocateHelpPage.js | 11 ++++
client/src/components/pages/advocate/index.js | 1 +
.../components/pages/provider/ProviderHelpPage.js | 73 +++++++++++++++++++++
client/src/components/pages/provider/index.js | 1 +
client/src/routes/AdvocateRoutes.js | 4 +-
client/src/routes/ProviderRoutes.js | 4 +-
configdist.py | 3 +
21 files changed, 244 insertions(+), 81 deletions(-)

**Comment by nobane** [comment]
The site is not ready for deployment. The plan was to notify OSLC when the fixes were all in and tested. We currently have one last fix, a fairly big one, about to be merged in. After it is merged we will test it. Once we have tested, we will notify OSLC that we're ready to roll out an update. 

As stated in the CHANGELOG file, this version is currently *unreleased*. The CHANGELOG is a good place to look at where current development is.

Please set the code back to a previous commit until we notify OSLC that we're ready to deploy these updates (the goal for that is today, after the final fix is in and we have tested the site). I recommend `4069b2ff4086c5526fe2b42ce3d1209ef6fc4a5c`.

**Comment by nobane** [comment]
In the future, we would like to have two main branches, `develop` and `master`:

`develop` would be where we are merging in our latest code, building up a release in the CHANGELOG.

`master` would be for when we feel the code is stable and ready for a release. The version number in the CHANGELOG will be pinned and we will merge `develop` into `master`, signalling a release has been made.

It would be wise to first review the CHANGELOG when deploying a new release, as a high-level summary of changes will be there, including changes to the config file or database.

**Comment by oslcit** [comment]
Thanks for the info and follow up. We rolled back the version this morning and got things back up and running. The plan for a stable release and dev branch is fantastic and will definitely help me when I am tasked with updating the RAN server in the future. I will track the Changelog going forward.


Thanks,


Dylan Treon
User Support Technician
Oregon Social Learning Center<http://www.oslc.org/>, TFC Oregon<http://www.tfcoregon.com/>, ISII<http://www.isii.net/>, OSLC Developments Inc<http://www.oslcdevelopments.org/>
Office 244
10 Shelton-McMurphey Blvd, Eugene OR 97401
(541) 485-2711 Ext. 1198
https://support.oslc.org/portal/portal-login
